spring:
  application:
    name: payflow
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_db
    username: postgres
    password: nitesh1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

payflow:
  jwt:
    secret: "ThisIsADemoSecretKeyForPayFlowJWTSigningChangeInProd123456"
    expiration-ms: 900000
  admin:
    username: "admin"
    password: "admin123"